name: Prod Application CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable_cicd.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
